# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:24
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
                ('game_category', models.CharField(max_length=20)),
                ('game_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game_date', models.DateField(blank=True)),
                ('game_description', models.CharField(max_length=255)),
                ('game_sale', models.IntegerField(default=0, max_length=10)),
                ('game_pic', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=b'')),
                ('game_path', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=255)),
                ('save_score', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_category', models.CharField(default=2, max_length=2)),
                ('user_image', models.CharField(blank=True, max_length=150, null=True)),
                ('user_valid', models.BooleanField(default=False)),
                ('user_dev_games', models.CharField(blank=True, default='/', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, to='game.User'),
        ),
    ]
